apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: kafka-broker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
      - name: kafka-broker
        image: confluentinc/cp-kafka:7.2.3
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: kafka-broker-service:9092
        - name: KAFKA_BROKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
              apiVersion: v1
---
apiVersion: v1
kind: Service
metadata:
  namespace: confluent
  name: kafka-broker-service
spec:
  selector:
    app: kafka-broker
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
